version: '3.8'

services:
  math-app:
    build: .
    container_name: math_app
    ports:
      - '3040:3040'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
