apiVersion: v1
kind: Service
metadata:
  name: node-web
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:
    - port: 80 # Service port (what you’ll forward to)
      targetPort: 3040 # Container port (what your app listens on)
